# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'g:\You_Mind\python\source\test2.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(74, 0, 561, 721))
        self.stackedWidget.setMinimumSize(QtCore.QSize(441, 721))
        self.stackedWidget.setStyleSheet("background-color : rgb(242,242,242);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_link = QtWidgets.QWidget()
        self.page_link.setObjectName("page_link")
        self.btn_link_download = QtWidgets.QPushButton(self.page_link)
        self.btn_link_download.setGeometry(QtCore.QRect(380, 680, 171, 31))
        self.btn_link_download.setObjectName("btn_link_download")
        self.combo_link_format = QtWidgets.QComboBox(self.page_link)
        self.combo_link_format.setGeometry(QtCore.QRect(10, 680, 176, 31))
        self.combo_link_format.setObjectName("combo_link_format")
        self.btn_link_file = QtWidgets.QPushButton(self.page_link)
        self.btn_link_file.setGeometry(QtCore.QRect(520, 640, 31, 31))
        self.btn_link_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_link_file.setStyleSheet("QPushButton{image:url(./image/folder1.png); border:0px; background-color : rgba(0,0,0,0);}\n"
"QPushButton:hover{image:url(./image/folder2.png); border:0px;background-color : rgba(0,0,0,0);}")
        self.btn_link_file.setText("")
        self.btn_link_file.setObjectName("btn_link_file")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_link)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 640, 501, 31))
        self.lineEdit_2.setStyleSheet("background-color : white; border:0px;")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.combo_link_format_2 = QtWidgets.QComboBox(self.page_link)
        self.combo_link_format_2.setGeometry(QtCore.QRect(200, 680, 171, 31))
        self.combo_link_format_2.setObjectName("combo_link_format_2")
        self.combo_link_format_2.addItem("")
        self.combo_link_format_2.addItem("")
        self.combo_link_format_2.addItem("")
        self.combo_link_format_2.addItem("")
        self.panel_link = QtWidgets.QScrollArea(self.page_link)
        self.panel_link.setGeometry(QtCore.QRect(-10, 70, 561, 561))
        self.panel_link.setWidgetResizable(True)
        self.panel_link.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.panel_link.setObjectName("panel_link")
        self.layout_link_data = QtWidgets.QWidget()
        self.layout_link_data.setGeometry(QtCore.QRect(0, 0, 559, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layout_link_data.sizePolicy().hasHeightForWidth())
        self.layout_link_data.setSizePolicy(sizePolicy)
        self.layout_link_data.setObjectName("layout_link_data")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layout_link_data)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.panel_link.setWidget(self.layout_link_data)
        self.asdf_2 = QtWidgets.QLabel(self.page_link)
        self.asdf_2.setGeometry(QtCore.QRect(0, 10, 551, 51))
        self.asdf_2.setObjectName("asdf_2")
        self.stackedWidget.addWidget(self.page_link)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_3)
        self.scrollArea_2.setGeometry(QtCore.QRect(20, 60, 411, 651))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 98, 966))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_12 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_12.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_12.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_12.setObjectName("widget_12")
        self.label_60 = QtWidgets.QLabel(self.widget_12)
        self.label_60.setGeometry(QtCore.QRect(90, 10, 231, 31))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.widget_12)
        self.label_61.setGeometry(QtCore.QRect(0, 10, 80, 80))
        self.label_61.setStyleSheet("background-color : black ;")
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.widget_12)
        self.label_62.setGeometry(QtCore.QRect(90, 50, 241, 16))
        self.label_62.setObjectName("label_62")
        self.progressBar_15 = QtWidgets.QProgressBar(self.widget_12)
        self.progressBar_15.setGeometry(QtCore.QRect(90, 70, 291, 23))
        self.progressBar_15.setMaximum(100)
        self.progressBar_15.setProperty("value", 44)
        self.progressBar_15.setObjectName("progressBar_15")
        self.label_63 = QtWidgets.QLabel(self.widget_12)
        self.label_63.setGeometry(QtCore.QRect(320, 10, 61, 21))
        self.label_63.setObjectName("label_63")
        self.verticalLayout_4.addWidget(self.widget_12)
        self.widget_11 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_11.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_11.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_11.setObjectName("widget_11")
        self.label_56 = QtWidgets.QLabel(self.widget_11)
        self.label_56.setGeometry(QtCore.QRect(90, 10, 231, 31))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.widget_11)
        self.label_57.setGeometry(QtCore.QRect(0, 10, 80, 80))
        self.label_57.setStyleSheet("background-color : black ;")
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.widget_11)
        self.label_58.setGeometry(QtCore.QRect(90, 50, 241, 16))
        self.label_58.setObjectName("label_58")
        self.progressBar_14 = QtWidgets.QProgressBar(self.widget_11)
        self.progressBar_14.setGeometry(QtCore.QRect(90, 70, 291, 23))
        self.progressBar_14.setMaximum(100)
        self.progressBar_14.setProperty("value", 44)
        self.progressBar_14.setObjectName("progressBar_14")
        self.label_59 = QtWidgets.QLabel(self.widget_11)
        self.label_59.setGeometry(QtCore.QRect(320, 10, 61, 21))
        self.label_59.setObjectName("label_59")
        self.verticalLayout_4.addWidget(self.widget_11)
        self.widget_9 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_9.setObjectName("widget_9")
        self.label_44 = QtWidgets.QLabel(self.widget_9)
        self.label_44.setGeometry(QtCore.QRect(90, 10, 231, 31))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.widget_9)
        self.label_45.setGeometry(QtCore.QRect(0, 10, 80, 80))
        self.label_45.setStyleSheet("background-color : black ;")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.widget_9)
        self.label_46.setGeometry(QtCore.QRect(90, 50, 241, 16))
        self.label_46.setObjectName("label_46")
        self.progressBar_11 = QtWidgets.QProgressBar(self.widget_9)
        self.progressBar_11.setGeometry(QtCore.QRect(90, 70, 291, 23))
        self.progressBar_11.setMaximum(100)
        self.progressBar_11.setProperty("value", 44)
        self.progressBar_11.setObjectName("progressBar_11")
        self.label_47 = QtWidgets.QLabel(self.widget_9)
        self.label_47.setGeometry(QtCore.QRect(320, 10, 61, 21))
        self.label_47.setObjectName("label_47")
        self.verticalLayout_4.addWidget(self.widget_9)
        self.widget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_8.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_8.setObjectName("widget_8")
        self.label_40 = QtWidgets.QLabel(self.widget_8)
        self.label_40.setGeometry(QtCore.QRect(90, 10, 231, 31))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.widget_8)
        self.label_41.setGeometry(QtCore.QRect(0, 10, 80, 80))
        self.label_41.setStyleSheet("background-color : black ;")
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.widget_8)
        self.label_42.setGeometry(QtCore.QRect(90, 50, 241, 16))
        self.label_42.setObjectName("label_42")
        self.progressBar_10 = QtWidgets.QProgressBar(self.widget_8)
        self.progressBar_10.setGeometry(QtCore.QRect(90, 70, 291, 23))
        self.progressBar_10.setMaximum(100)
        self.progressBar_10.setProperty("value", 44)
        self.progressBar_10.setObjectName("progressBar_10")
        self.label_43 = QtWidgets.QLabel(self.widget_8)
        self.label_43.setGeometry(QtCore.QRect(320, 10, 61, 21))
        self.label_43.setObjectName("label_43")
        self.verticalLayout_4.addWidget(self.widget_8)
        self.widget_10 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_10.setObjectName("widget_10")
        self.label_52 = QtWidgets.QLabel(self.widget_10)
        self.label_52.setGeometry(QtCore.QRect(90, 10, 231, 31))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.widget_10)
        self.label_53.setGeometry(QtCore.QRect(0, 10, 80, 80))
        self.label_53.setStyleSheet("background-color : black ;")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.widget_10)
        self.label_54.setGeometry(QtCore.QRect(90, 50, 241, 16))
        self.label_54.setObjectName("label_54")
        self.progressBar_13 = QtWidgets.QProgressBar(self.widget_10)
        self.progressBar_13.setGeometry(QtCore.QRect(90, 70, 291, 23))
        self.progressBar_13.setMaximum(100)
        self.progressBar_13.setProperty("value", 44)
        self.progressBar_13.setObjectName("progressBar_13")
        self.label_55 = QtWidgets.QLabel(self.widget_10)
        self.label_55.setGeometry(QtCore.QRect(320, 10, 61, 21))
        self.label_55.setObjectName("label_55")
        self.verticalLayout_4.addWidget(self.widget_10)
        self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_6.setObjectName("widget_6")
        self.label_36 = QtWidgets.QLabel(self.widget_6)
        self.label_36.setGeometry(QtCore.QRect(90, 10, 231, 31))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.widget_6)
        self.label_37.setGeometry(QtCore.QRect(0, 10, 80, 80))
        self.label_37.setStyleSheet("background-color : black ;")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.widget_6)
        self.label_38.setGeometry(QtCore.QRect(90, 50, 241, 16))
        self.label_38.setObjectName("label_38")
        self.progressBar_9 = QtWidgets.QProgressBar(self.widget_6)
        self.progressBar_9.setGeometry(QtCore.QRect(90, 70, 291, 23))
        self.progressBar_9.setMaximum(100)
        self.progressBar_9.setProperty("value", 44)
        self.progressBar_9.setObjectName("progressBar_9")
        self.label_39 = QtWidgets.QLabel(self.widget_6)
        self.label_39.setGeometry(QtCore.QRect(320, 10, 61, 21))
        self.label_39.setObjectName("label_39")
        self.verticalLayout_4.addWidget(self.widget_6)
        self.widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_5.setObjectName("widget_5")
        self.label_28 = QtWidgets.QLabel(self.widget_5)
        self.label_28.setGeometry(QtCore.QRect(90, 10, 231, 31))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.widget_5)
        self.label_29.setGeometry(QtCore.QRect(0, 10, 80, 80))
        self.label_29.setStyleSheet("background-color : black ;")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.widget_5)
        self.label_30.setGeometry(QtCore.QRect(90, 50, 241, 16))
        self.label_30.setObjectName("label_30")
        self.progressBar_7 = QtWidgets.QProgressBar(self.widget_5)
        self.progressBar_7.setGeometry(QtCore.QRect(90, 70, 291, 23))
        self.progressBar_7.setMaximum(100)
        self.progressBar_7.setProperty("value", 44)
        self.progressBar_7.setObjectName("progressBar_7")
        self.label_31 = QtWidgets.QLabel(self.widget_5)
        self.label_31.setGeometry(QtCore.QRect(320, 10, 61, 21))
        self.label_31.setObjectName("label_31")
        self.verticalLayout_4.addWidget(self.widget_5)
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_4.setObjectName("widget_4")
        self.label_20 = QtWidgets.QLabel(self.widget_4)
        self.label_20.setGeometry(QtCore.QRect(90, 10, 231, 31))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.widget_4)
        self.label_21.setGeometry(QtCore.QRect(0, 10, 80, 80))
        self.label_21.setStyleSheet("background-color : black ;")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_4)
        self.label_22.setGeometry(QtCore.QRect(90, 50, 241, 16))
        self.label_22.setObjectName("label_22")
        self.progressBar_5 = QtWidgets.QProgressBar(self.widget_4)
        self.progressBar_5.setGeometry(QtCore.QRect(90, 70, 291, 23))
        self.progressBar_5.setMaximum(100)
        self.progressBar_5.setProperty("value", 44)
        self.progressBar_5.setObjectName("progressBar_5")
        self.label_23 = QtWidgets.QLabel(self.widget_4)
        self.label_23.setGeometry(QtCore.QRect(320, 10, 61, 21))
        self.label_23.setObjectName("label_23")
        self.verticalLayout_4.addWidget(self.widget_4)
        self.widget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 100))
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_7.setObjectName("widget_7")
        self.label_32 = QtWidgets.QLabel(self.widget_7)
        self.label_32.setGeometry(QtCore.QRect(90, 10, 231, 31))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.widget_7)
        self.label_33.setGeometry(QtCore.QRect(0, 10, 80, 80))
        self.label_33.setStyleSheet("background-color : black ;")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.widget_7)
        self.label_34.setGeometry(QtCore.QRect(90, 50, 241, 16))
        self.label_34.setObjectName("label_34")
        self.progressBar_8 = QtWidgets.QProgressBar(self.widget_7)
        self.progressBar_8.setGeometry(QtCore.QRect(90, 70, 291, 23))
        self.progressBar_8.setMaximum(100)
        self.progressBar_8.setProperty("value", 44)
        self.progressBar_8.setObjectName("progressBar_8")
        self.label_35 = QtWidgets.QLabel(self.widget_7)
        self.label_35.setGeometry(QtCore.QRect(340, 10, 61, 21))
        self.label_35.setObjectName("label_35")
        self.verticalLayout_4.addWidget(self.widget_7)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 341, 41))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_3.setGeometry(QtCore.QRect(20, 40, 411, 651))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 409, 649))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.stackedWidget.addWidget(self.page_2)
        self.widget_17 = QtWidgets.QWidget(self.centralwidget)
        self.widget_17.setGeometry(QtCore.QRect(0, 0, 71, 721))
        self.widget_17.setStyleSheet("background-color(237,237,245);")
        self.widget_17.setObjectName("widget_17")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget_17)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 71, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_link = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_link.sizePolicy().hasHeightForWidth())
        self.btn_link.setSizePolicy(sizePolicy)
        self.btn_link.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_link.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_link.setStyleSheet("QPushButton{image:url(./image/link1.png); border:0px; background-color : rgba(0,0,0,0);}\n"
"QPushButton:hover{image:url(./image/link2.png); border:0px;background-color : rgba(0,0,0,0);}\n"
"QPushButton:checked{image:url(./image/link2.png); border:0px;background-color : rgba(0,0,0,0);}")
        self.btn_link.setText("")
        self.btn_link.setCheckable(True)
        self.btn_link.setChecked(False)
        self.btn_link.setObjectName("btn_link")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.btn_link)
        self.verticalLayout_2.addWidget(self.btn_link)
        self.btn_sub = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_sub.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_sub.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sub.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn_sub.setStyleSheet("QPushButton{image:url(./image/sub1.png); border:0px; background-color : rgba(0,0,0,0);}\n"
"QPushButton:hover{image:url(./image/sub2.png); border:0px;background-color : rgba(0,0,0,0);}\n"
"QPushButton:checked{image:url(./image/sub2.png); border:0px;background-color : rgba(0,0,0,0);}")
        self.btn_sub.setText("")
        self.btn_sub.setCheckable(True)
        self.btn_sub.setObjectName("btn_sub")
        self.buttonGroup.addButton(self.btn_sub)
        self.verticalLayout_2.addWidget(self.btn_sub)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setCheckable(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.buttonGroup.addButton(self.pushButton_3)
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.buttonGroup.addButton(self.pushButton_4)
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setMinimumSize(QtCore.QSize(50, 50))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.buttonGroup.addButton(self.pushButton_5)
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.widget_18 = QtWidgets.QWidget(self.centralwidget)
        self.widget_18.setGeometry(QtCore.QRect(639, -1, 641, 721))
        self.widget_18.setStyleSheet("background-color : rgb(245,245,245);")
        self.widget_18.setObjectName("widget_18")
        self.asdf = QtWidgets.QLabel(self.widget_18)
        self.asdf.setGeometry(QtCore.QRect(10, 10, 621, 51))
        self.asdf.setObjectName("asdf")
        self.now_download_scroll = QtWidgets.QScrollArea(self.widget_18)
        self.now_download_scroll.setGeometry(QtCore.QRect(0, 70, 641, 641))
        self.now_download_scroll.setWidgetResizable(True)
        self.now_download_scroll.setObjectName("now_download_scroll")
        self.now_download_layout = QtWidgets.QWidget()
        self.now_download_layout.setGeometry(QtCore.QRect(0, 0, 639, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.now_download_layout.sizePolicy().hasHeightForWidth())
        self.now_download_layout.setSizePolicy(sizePolicy)
        self.now_download_layout.setObjectName("now_download_layout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.now_download_layout)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.now_panel = QtWidgets.QWidget(self.now_download_layout)
        self.now_panel.setMinimumSize(QtCore.QSize(0, 120))
        self.now_panel.setMaximumSize(QtCore.QSize(16777215, 120))
        self.now_panel.setObjectName("now_panel")
        self.now_image = QtWidgets.QLabel(self.now_panel)
        self.now_image.setGeometry(QtCore.QRect(10, 10, 160, 90))
        self.now_image.setStyleSheet("background-color : black ;")
        self.now_image.setObjectName("now_image")
        self.now_bar = QtWidgets.QProgressBar(self.now_panel)
        self.now_bar.setGeometry(QtCore.QRect(180, 80, 431, 20))
        font = QtGui.QFont()
        font.setFamily("서울남산체 M")
        self.now_bar.setFont(font)
        self.now_bar.setStyleSheet("QProgressBar {\n"
"     border: 2px solid grey;\n"
"     border-radius: 5px;\n"
"     background-color: #FFFFFF;\n"
"     text-color : rgb(128,128,128);\n"
"}\n"
"\n"
" QProgressBar::chunk {\n"
"     background-color: #A293BD;\n"
"     width: 20px;\n"
" }")
        self.now_bar.setProperty("value", 58)
        self.now_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.now_bar.setObjectName("now_bar")
        self.now_youtube_icon = QtWidgets.QLabel(self.now_panel)
        self.now_youtube_icon.setGeometry(QtCore.QRect(180, 55, 21, 21))
        self.now_youtube_icon.setStyleSheet("image:url(./image/sub1.png);")
        self.now_youtube_icon.setText("")
        self.now_youtube_icon.setObjectName("now_youtube_icon")
        self.now_title = QtWidgets.QLabel(self.now_panel)
        self.now_title.setGeometry(QtCore.QRect(178, 10, 421, 51))
        font = QtGui.QFont()
        font.setFamily("서울남산체 EB")
        font.setPointSize(12)
        self.now_title.setFont(font)
        self.now_title.setScaledContents(False)
        self.now_title.setWordWrap(True)
        self.now_title.setObjectName("now_title")
        self.now_id = QtWidgets.QLabel(self.now_panel)
        self.now_id.setGeometry(QtCore.QRect(208, 55, 351, 20))
        font = QtGui.QFont()
        font.setFamily("서울남산체 M")
        font.setPointSize(9)
        self.now_id.setFont(font)
        self.now_id.setObjectName("now_id")
        self.now_image.raise_()
        self.now_bar.raise_()
        self.now_title.raise_()
        self.now_id.raise_()
        self.now_youtube_icon.raise_()
        self.verticalLayout_6.addWidget(self.now_panel)
        self.now_download_scroll.setWidget(self.now_download_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.btn_link.clicked.connect(MainWindow.btn_link_event)
        self.btn_sub.clicked.connect(MainWindow.btn_sub_event)
        self.btn_link_file.clicked.connect(MainWindow.btn_file_chooser_event)
        self.btn_link_download.clicked.connect(MainWindow.btn_download_event)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_link_download.setText(_translate("MainWindow", "다운로드"))
        self.combo_link_format_2.setItemText(0, _translate("MainWindow", "1080p - 17.75MB"))
        self.combo_link_format_2.setItemText(1, _translate("MainWindow", "720p - 17.75MB"))
        self.combo_link_format_2.setItemText(2, _translate("MainWindow", "480p 60ps - 12.5MB"))
        self.combo_link_format_2.setItemText(3, _translate("MainWindow", "장민석 - 신상호"))
        self.asdf_2.setText(_translate("MainWindow", "재생목록 / 동영상 선택"))
        self.label_60.setText(_translate("MainWindow", "채널이름"))
        self.label_61.setText(_translate("MainWindow", "썸네일ㄴㅇㄹㄴㅇㄹㄴㅇㄹ"))
        self.label_62.setText(_translate("MainWindow", "채널 구독자"))
        self.progressBar_15.setFormat(_translate("MainWindow", "%p%"))
        self.label_63.setText(_translate("MainWindow", "1/10"))
        self.label_56.setText(_translate("MainWindow", "나중에 동적생성할거임 일단 테스트 ㅇㅅㅇ"))
        self.label_57.setText(_translate("MainWindow", "썸네일ㄴㅇㄹㄴㅇㄹㄴㅇㄹ"))
        self.label_58.setText(_translate("MainWindow", "채널 구독자"))
        self.progressBar_14.setFormat(_translate("MainWindow", "%p%"))
        self.label_59.setText(_translate("MainWindow", "1/10"))
        self.label_44.setText(_translate("MainWindow", "채널이름"))
        self.label_45.setText(_translate("MainWindow", "썸네일ㄴㅇㄹㄴㅇㄹㄴㅇㄹ"))
        self.label_46.setText(_translate("MainWindow", "채널 구독자"))
        self.progressBar_11.setFormat(_translate("MainWindow", "%p%"))
        self.label_47.setText(_translate("MainWindow", "1/10"))
        self.label_40.setText(_translate("MainWindow", "채널이름"))
        self.label_41.setText(_translate("MainWindow", "썸네일ㄴㅇㄹㄴㅇㄹㄴㅇㄹ"))
        self.label_42.setText(_translate("MainWindow", "채널 구독자"))
        self.progressBar_10.setFormat(_translate("MainWindow", "%p%"))
        self.label_43.setText(_translate("MainWindow", "1/10"))
        self.label_52.setText(_translate("MainWindow", "채널이름"))
        self.label_53.setText(_translate("MainWindow", "썸네일ㄴㅇㄹㄴㅇㄹㄴㅇㄹ"))
        self.label_54.setText(_translate("MainWindow", "채널 구독자"))
        self.progressBar_13.setFormat(_translate("MainWindow", "%p%"))
        self.label_55.setText(_translate("MainWindow", "1/10"))
        self.label_36.setText(_translate("MainWindow", "채널이름"))
        self.label_37.setText(_translate("MainWindow", "썸네일ㄴㅇㄹㄴㅇㄹㄴㅇㄹ"))
        self.label_38.setText(_translate("MainWindow", "채널 구독자"))
        self.progressBar_9.setFormat(_translate("MainWindow", "%p%"))
        self.label_39.setText(_translate("MainWindow", "1/10"))
        self.label_28.setText(_translate("MainWindow", "채널이름"))
        self.label_29.setText(_translate("MainWindow", "썸네일ㄴㅇㄹㄴㅇㄹㄴㅇㄹ"))
        self.label_30.setText(_translate("MainWindow", "채널 구독자"))
        self.progressBar_7.setFormat(_translate("MainWindow", "%p%"))
        self.label_31.setText(_translate("MainWindow", "1/10"))
        self.label_20.setText(_translate("MainWindow", "채널이름"))
        self.label_21.setText(_translate("MainWindow", "썸네일ㄴㅇㄹㄴㅇㄹㄴㅇㄹ"))
        self.label_22.setText(_translate("MainWindow", "채널 구독자"))
        self.progressBar_5.setFormat(_translate("MainWindow", "%p%"))
        self.label_23.setText(_translate("MainWindow", "1/10"))
        self.label_32.setText(_translate("MainWindow", "채널이름"))
        self.label_33.setText(_translate("MainWindow", "썸네일ㄴㅇㄹㄴㅇㄹㄴㅇㄹ"))
        self.label_34.setText(_translate("MainWindow", "채널 구독자"))
        self.progressBar_8.setFormat(_translate("MainWindow", "%p%"))
        self.label_35.setText(_translate("MainWindow", "1/10"))
        self.label_4.setText(_translate("MainWindow", "구도곡ㄷ고독도곧고"))
        self.lineEdit.setText(_translate("MainWindow", "재생목록은 일단 나중에 할게"))
        self.pushButton_3.setText(_translate("MainWindow", "예비1"))
        self.pushButton_4.setText(_translate("MainWindow", "예비2"))
        self.pushButton_5.setText(_translate("MainWindow", "예비3"))
        self.asdf.setText(_translate("MainWindow", "현재다운로드 목록"))
        self.now_image.setText(_translate("MainWindow", "썸네일ㄴㅇㄹㄴㅇㄹㄴㅇㄹ"))
        self.now_bar.setFormat(_translate("MainWindow", "%p%"))
        self.now_title.setText(_translate("MainWindow", "\'사탄 : 아 이건 좀;;, 사탄 드립\'은 어디서 나온 말일까?ㄴㅇㄹㄴㅇㄹㄴㅇㄹ"))
        self.now_id.setText(_translate("MainWindow", "https://www.youtube.com/watch?v=P9J87Bxdtg8"))

